# Generated by Django 4.0.3 on 2022-03-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0003_project_remove_photo_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
