# Generated by Django 4.0.3 on 2022-03-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawards', '0004_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(default='', max_length=140),
        ),
    ]
